In [3]:
# https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

# Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

from __future__ import print_function
import torch

In [4]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.9310, 0.7773, 0.7220],
        [0.9605, 0.3005, 0.0890],
        [0.0208, 0.2003, 0.4817],
        [0.4146, 0.3632, 0.3890],
        [0.5418, 0.7019, 0.7741]])


In [7]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
# or create a tensor based on an existing tensor.
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0859,  0.7116, -0.9343],
        [ 1.0143,  0.3507,  0.1164],
        [-0.5411, -1.6098,  0.6139],
        [-0.4894, -0.7585, -0.7915],
        [ 0.3111,  0.5390,  0.2806]])


In [13]:
# Get it's size
print(x.size())

torch.Size([5, 3])


In [24]:
# Addition: syntax 2
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8546, 1.2380, 0.7409],
        [0.7467, 1.0235, 0.9503],
        [1.3407, 1.0058, 0.9840],
        [1.1685, 0.6560, 1.0702],
        [1.4278, 0.9972, 1.2202]])


In [16]:
# Addition: providing an output tensor as argument
print(torch.add(x, y))

tensor([[ 1.8131,  1.4201, -0.1976],
        [ 1.4395,  0.5434,  0.2846],
        [-0.4153, -1.6047,  1.5008],
        [ 0.2094, -0.3828, -0.7887],
        [ 0.7237,  1.3122,  1.0015]])


In [17]:
# Addition: in-place
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.8131,  1.4201, -0.1976],
        [ 1.4395,  0.5434,  0.2846],
        [-0.4153, -1.6047,  1.5008],
        [ 0.2094, -0.3828, -0.7887],
        [ 0.7237,  1.3122,  1.0015]])


In [18]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.8131,  1.4201, -0.1976],
        [ 1.4395,  0.5434,  0.2846],
        [-0.4153, -1.6047,  1.5008],
        [ 0.2094, -0.3828, -0.7887],
        [ 0.7237,  1.3122,  1.0015]])


In [19]:
# You can use all the bells and whistles of NumPy-like indexes
print(x[:, 1])

tensor([ 0.7116,  0.3507, -1.6098, -0.7585,  0.5390])


In [21]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 0.4546, -0.3030,  0.8018, -0.1188],
        [ 0.6284, -1.0899,  0.5839, -0.9634],
        [-1.1746, -1.3331, -0.1949, -1.7900],
        [-1.1318, -0.7031,  0.4702, -2.0718]])
tensor([ 0.4546, -0.3030,  0.8018, -0.1188,  0.6284, -1.0899,  0.5839, -0.9634,
        -1.1746, -1.3331, -0.1949, -1.7900, -1.1318, -0.7031,  0.4702, -2.0718])
tensor([[ 0.4546, -0.3030,  0.8018, -0.1188,  0.6284, -1.0899,  0.5839, -0.9634],
        [-1.1746, -1.3331, -0.1949, -1.7900, -1.1318, -0.7031,  0.4702, -2.0718]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6321])
0.6320607662200928


In [25]:
# NumPy Bridge

# Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

# The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.
# Converting a Torch Tensor to a NumPy Array

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [27]:
b = a.numpy()
print(b)

[2. 2. 2. 2. 2.]


In [28]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [29]:
# Converting NumPy Array to Torch Tensor

# See how changing the np array changed the Torch Tensor automatically
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [30]:
# All the Tensors on the CPU except a CharTensor support converting to NumPy and back.
# CUDA Tensors

# Tensors can be moved onto any device using the .to method.
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!